# Generated by Django 4.2.4 on 2023-08-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_item', models.CharField(choices=[('Banana', 'Banana'), ('Apple', 'Apple'), ('Orange', 'Orange'), ('Mango', 'Mango')], max_length=50)),
                ('available_quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='purchase',
            name='item',
            field=models.CharField(choices=[('Banana', 'Banana'), ('Apple', 'Apple'), ('Orange', 'Orange'), ('Mango', 'Mango')], max_length=50),
        ),
    ]
